sudo: false

services:
  # -

language: node_js
node_js:
  - stable

env:
  global:
    - NAME="android-colors"
    - DEPLOY_BRANCH="master"
    - SSH_KEY="deployment"
    - GIT_NAME="travis"
    - GIT_EMAIL="deploy@travis-ci.org"

cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_293649c28335_key -iv $encrypted_293649c28335_iv
    -in deployment.enc -out deployment -d
  # - set -e  # stop the execution of a script if a command or pipeline has an error
  # - set -x  # all executed commands are printed to the terminal (serves for debugging :muscle:)

script:
  - set -e
  - npm install --silent --progress=false
  - ./node_modules/.bin/eslint ./src --cache
  # - npm run test
  - source scripts/deploy.sh

after_script:
  # -

after_success:
  # -

branches:
  # only:
    # - master
  except:
    - gh-pages

notifications:
  email: false
  # slack:
    # on_success: change
    # on_failure: always
    # on_pull_requests: true
    # rooms:
    #   - secure: ""
